---
apiVersion: v1
kind: Service
metadata:
  name: wechat-commander
  namespace: yunwei
spec:
  ports:
  - name: web
    port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: wechat-commander
  sessionAffinity: ClientIP
# we use extra nginx, since it need external ip
#
# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wechat-commander
  namespace: yunwei
  # annotations:
    #traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: wechat-commander.newops.haodai.net
    http:
      paths:
      - path: /
        backend:
          serviceName: wechat-commander
          servicePort: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wechat-commander
  namespace: yunwei
  labels:
    app: wechat-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wechat-commander
  template:
    metadata:
      labels:
        app: wechat-commander
    spec:
      containers:
        - name: wechat-commander
          image: harbor.haodai.net/ops/wechat-commander:v1
          imagePullPolicy: Always
          # command: ["/bin/sh","-c","sleep 3600000"]
          ports:
          - containerPort: 4000
      nodeSelector:
        #kubernetes.io/hostname: 172.31.90.208
        func: monitor
        # env: yunwei
